### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by WynZemp** [fahs16/autoceng#1]
your website doesn't have any details about this
also keep saying device down

**Comment by fahs16** [comment]
hi i'am sorry for late reply,

make sure you can ping from your workstation to router.
if your router does'nt permit ping, you can edit line 126 to this :

before : verifdevice(dd[0],int(dd[1]),dd[2].strip(),dd[3].strip()) 
after : eksekusi(dd[0],int(dd[1]),dd[2].strip(),dd[3].strip())

I just had time to upload the manual page yesterday on this link https://www.hudzaifah.net/2020/06/autoceng-mikrotik-automation-en.html
